### ISSUE TITLE
Problems with ldap-record

### ISSUE THREAD

**Issue by sinnbeck** [discoverydesign/filament-gaze#11]
I am working on a project that uses ldap-record for auth. That is presenting some problems with this package sadly. 

https://github.com/discoverydesign/filament-gaze/blob/main/src/Forms/Components/GazeBanner.php#L186

Here it uses the LdapModel which means on line 194 it searches on ldap, instead of the database.

A suggestion would be to allow us to set the class to use in either a config file or when instantiating the plugin

Let me know if you would want me to make a PR :)

**Comment by discoveryjames** [comment]
Hey @sinnbeck

I've refactored things a little and it should resolve the issue :)

Give 1.1.5 a go and let me know if you have any issues.

**Comment by sinnbeck** [comment]
Awesome. I'll give it a try as soon as possible!
