### ISSUE TITLE
Small bug in the gaze locking mechanism

### ISSUE THREAD

**Issue by matheusjohannaraujo** [discoverydesign/filament-gaze#2]
I found a small bug in the gaze locking mechanism. When two users attempt to access or edit the same record, the system behaves as expected: it grants access to one user and blocks the other (so far, so good!). However, the issue arises when the blocked user is released after the first user's edits. The previously blocked user doesn't see the changes and ends up overwriting the previous user's modifications. A potential solution would be to implement an automatic data refresh mechanism before the blocked user is released for editing.

**Comment by discoveryjames** [comment]
Hey @matheusjohannaraujo

Thanks for flagging this. I believe we resolved this in the latest version, can you confirm if you are using the latest version? If not, let me know and I'll take a further look for you.

**Comment by matheusjohannaraujo** [comment]
![image](https://github.com/user-attachments/assets/aed8af9b-34dd-4002-ad52-99c167c87c36)

**Comment by discoveryjames** [comment]
Thanks for confirming. We'll take a look for you.

How complicated is your Resource Form? Straight forward or do you have a lot of different inputs?

**Comment by matheusjohannaraujo** [comment]
A simple user edit form with only text fields, select boxes, and checkboxes. A straightforward form!

**Comment by matheusjohannaraujo** [comment]
![image](https://github.com/user-attachments/assets/79b20821-2956-4531-94a9-88d77d9b7f92)

**Comment by 0wain** [comment]
Hey @matheusjohannaraujo,

The latest version should fix your issue.

Please give it a try and if it doesn't, feel free to reopen.

Thanks for taking the time to report this.
