### ISSUE TITLE
No query results for model

### ISSUE THREAD

**Issue by troyeisert** [discoverydesign/filament-gaze#7]
When adding the GazeBanner with lock method `GazeBanner::make()->lock()`

I get the following error on my edit resource page.

`No query results for model [App\Models\Partners\PartnerArticle] 246`

Adding without lock seems to work well. But I need the lock functionality for my use case.

Any idea what the cause could be?

**Comment by 0wain** [comment]
Hey,

Let me look into this and get back to you asap.

**Comment by 0wain** [comment]
Hey,

Is there anything about your form that would be abnormal or is it all pretty standard? 

I can't seem to replicate your issue, so if you could maybe give a full error stack trace, that would be super useful. Anything to help diagnose or replicate this would be great.

Thanks in advance.

**Comment by troyeisert** [comment]
Thanks for looking into it. I found the issue. The model of this resource is using the method `getRouteKeyName()` to use the slug instead of the id as the key.

The id is being explicitly used here 
`
    public function refreshForm()
    {
        // Very hacky, maybe a better solution for this?
        $this->getLivewire()->mount($this->getRecord()?->id);
    }
 `
 
 I created a PR to fix this issue here: #10
